### ISSUE TITLE
Mod version showing 0.0NONE in mod menu

### ISSUE THREAD

**Issue by SkyeeeYT** [VazkiiMods/Patchouli#557] opened 2022-06-12 07:25 UTC
### Mod loader

Forge

### Minecraft version

1.18.2

### Patchouli version

1.18.2-69

### Modloader version

forge-40.1.48

### The latest.log file

2022-06-12-3.log.gz

### Issue description

On forge mod menu, i scroll down to patchouli and it shows the version is 0.0NONE??? patchouli is also the reason i am having frequent lag spikes in my game (it is still playable)

### Steps to reproduce

1. go to forge mod menu
2. go down to patchouli
3. notice 0.0NONE on the version column

**Comment by williewillus** [comment] 2022-06-12 08:02
Duplicate of #546

**Closed as completed by williewillus** 2022-06-12 08:02 UTC
Labels: bug
