### ISSUE TITLE
(1.19) Escape Key no longer closes book

### ISSUE THREAD

**Issue by baileyholl** [VazkiiMods/Patchouli#568] opened 2022-06-23 01:07 UTC
### Mod loader

Forge

### Minecraft version

1.19

### Patchouli version

1.19-72

### Modloader version

Forge: 41.0.38

### The latest.log file

https://pastebin.com/LmDLhH4k

### Issue description

Escape key no longer closes patchouli books, but 'e' does.

**Comment by williewillus** [comment] 2022-06-23 03:07
Cannot reproduce with just Patchouli and Forge

**Comment by aaronhowser1** [comment] 2022-06-23 08:25
I'm also having this, I'm also unable to leave with E unless I'm on the main page.

**Comment by williewillus** [comment] 2022-06-24 06:55
Fixed in 85a20b0e6f461213b1fa44062991bb75922ab8ef

**Closed as completed by williewillus** 2022-06-24 06:55 UTC
Labels: bug
