### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by HoodBlah** [VazkiiMods/Patchouli#544] opened 2022-05-29 22:49 UTC
### Mod loader

Forge

### Minecraft version

1.18.2

### Patchouli version

Patchouli-1.18.2-68

### Modloader version

Forge 40.1.25

### The latest.log file

https://gist.github.com/HoodBlah/7401fd77fcf1b456a2dde0cec7638ae3

### Issue description

Crashes on startup. Ik it's patchouli because if I have patchouli and optifine the game crashes, but without patchouli it works. It's hard to test the entire modpack without patchouli because of dependencies, but from what I tried, it works without it.

### Steps to reproduce

1. Install patchouli in mod folder
2. run minecraft

**Comment by williewillus** [comment] 2022-05-29 23:31
Duplicate of #543

**Closed as not planned by williewillus** 2022-05-29 23:31 UTC
Labels: bug
